"""
Main Application Entry Point.
This module sets up the FastAPI application and defines all the REST endpoints.
It acts as the glue between the HTTP requests, the database (StorageService), 
and the AI engine (LLMService).
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from app.services.llm import llm_service
from app.services.storage import storage
from app.models.storage import Session
from app.database import init_db
import json

# Initialize FastAPI application
app = FastAPI(
    title="VidyaLoop Socratic Tutor API",
    version="0.2.0" # Major upgrade to ChatGPT-equivalent async architecture
)

import os

# Enable CORS (Cross-Origin Resource Sharing)
# This allows our React frontend (running on a different port) to communicate with this backend.
cors_origin = os.getenv("FRONTEND_URL", "*")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[cors_origin],
    allow_credentials=(cors_origin != "*"),
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def startup_event():
    """
    Executes exactly once when the FastAPI server starts.
    We use this hook to initialize the SQLite database tables.
    """
    init_db()

class ChatRequest(BaseModel):
    """
    Schema for the incoming POST request payload when a student sends a message.
    """
    session_id: str
    message: str
    student_name: str = "Student"
    class_level: int = 11
    learner_type: str = "text"

@app.get("/")
def root():
    """Health check endpoint to verify the server is running."""
    return {"status": "VidyaLoop Tutor API is running (Async + SQLite Edition)"}

@app.get("/sessions")
def get_sessions():
    """
    Retrieves a list of all chat sessions to populate the frontend Sidebar.
    Returns metadata like `student_name`, `started_at`, and `message_count`.
    """
    return storage.list_sessions()

@app.get("/session/{session_id}/history")
def get_history(session_id: str):
    """
    Retrieves the entire conversation history for a specific session.
    Used by the frontend to reload past chats when the user clicks on a session in the Sidebar.
    """
    session = storage.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    messages = storage.get_messages(session_id)
    return {
        "session_id": session_id,
        "student_name": session.student_name,
        "class_level": session.class_level,
        "started_at": session.started_at.isoformat(),
        "messages": [
            {
                "role": m.role,
                "content": m.content,
                "created_at": m.created_at.isoformat()
            }
            for m in messages
        ]
    }

@app.delete("/session/{session_id}")
def delete_session(session_id: str):
    """
    Hard deletes a session and all its messages from the database.
    """
    success = storage.delete_session(session_id)
    if not success:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"status": "session deleted"}

@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    """
    The core endpoint for sending messages to the AI Tutor.
    It accepts a user message, ensures the session is registered in the database,
    and returns a StreamingResponse. 
    The StreamingResponse yields Server-Sent Events (SSE) from the `LLMService`,
    which allows the frontend to show the text typing out in real-time.
    """
    # 1. Ensure the session exists in the database before proceeding.
    session = storage.get_session(request.session_id)
    if not session:
        session = Session(
            session_id=request.session_id,
            student_name=request.student_name,
            class_level=request.class_level,
            learner_type=request.learner_type
        )
        storage.create_session(session)

    # 2. Return a stream that yields chunks of text generated by Ollama.
    return StreamingResponse(
        llm_service.get_response_stream(request.session_id, request.message), 
        media_type="text/event-stream"
    )