"""
Database Models Module.
This module defines the actual SQLite database tables using SQLAlchemy.
These models represent how data is physically stored on the disk.
"""

from sqlalchemy import Column, String, Integer, DateTime, Boolean, ForeignKey, Text
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database import Base

class SessionDB(Base):
    """
    Represents the `sessions` table in the database.
    Each row is a unique chat session between a student and the tutor.
    """
    __tablename__ = "sessions"

    # Primary key: A unique string identifier for the session
    session_id = Column(String, primary_key=True, index=True)
    
    # Student metadata
    student_name = Column(String, nullable=False)
    class_level = Column(Integer, nullable=False)
    learner_type = Column(String, default="text")
    
    # Timestamps and state
    started_at = Column(DateTime, default=datetime.utcnow)
    ended_at = Column(DateTime, nullable=True)
    is_active = Column(Boolean, default=True)

    # Relationship to messages. 'cascade="all, delete-orphan"' ensures that if a session is deleted,
    # all its associated messages are also deleted automatically.
    messages = relationship("MessageDB", back_populates="session", cascade="all, delete-orphan")

class MessageDB(Base):
    """
    Represents the `messages` table in the database.
    Each row is a single message (either from the user or the assistant) within a session.
    """
    __tablename__ = "messages"

    # Primary key for the message
    message_id = Column(String, primary_key=True, index=True)
    
    # Foreign key linking back to the sessions table
    session_id = Column(String, ForeignKey("sessions.session_id"))
    
    # 'user' or 'assistant'
    role = Column(String, nullable=False)
    
    # The actual markdown content generated by the user or LLM
    content = Column(Text, nullable=False)
    
    # Socratic hint tracking
    hint_count = Column(Integer, default=0)
    
    # Timestamp of when the message was sent
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship linking back to the parent session
    session = relationship("SessionDB", back_populates="messages")
